name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@0.0.0.0:5432/booklib

jobs:
  create_db:
    name: Create Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Run Postgres Container
        run: bash scripts/install_deps.sh && bash scripts/init_db.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: cargo test
